### PR TITLE
ISSUE#791: Added a timestamp format configuration

### PR DESCRIPTION
**Pull request by email2vimalraj**
User can set a required timestamp format through the report configuration. 

This is the feature request #791.

**Usage**:

```java
reporter.config().setTimeStampFormat("dd.MM.yyyy, HH:mm");
```

### CODE REVIEW

**Comment by anshooarora** [comment]
Thanks.  I will check a few scenarios and merge.

**Comment by email2vimalraj** [comment]
@anshooarora : I had fixed issue #811 also as part of this PR. See if you can merge both.

**Comment by anshooarora** [comment]
This does not accept the configuration:

```
ExtentHtmlReporter h = new ExtentHtmlReporter("Extent.html");
h.config().setTimeStampFormat("dd/mm/yyyy hh:mm:ss a");
```

Also, I see a few errors for this case (run twice to append):

```
ExtentHtmlReporter h = new ExtentHtmlReporter("Extent.html");
h.config().setTimeStampFormat("dd/mm/yyyy hh:mm:ss a");
h.setAppendExisting(true); // reparse values based on the expected timestamp

ExtentReports extent = new ExtentReports();
extent.attachReporter(h);

extent.createTest("Test").pass("Pass");
extent.flush();
```

**Comment by email2vimalraj** [comment]
@anshooarora : Good catch. This issue is bigger than I thought. Now I have to deal with Java date parsers :(

I'm looking into this and send the fix.

**Comment by email2vimalraj** [comment]
@anshooarora : I fixed the issue. Kindly revalidate and let me know your feedback.

**Comment by anshooarora** [comment]
Thanks!

**Comment by Rick-Repo** [comment]
Hello @anshooarora 
I have currently using the extentreports 3.0.2 
and I´m still having the "Unparseable date" issue.
The Project was running ok until the automatic summer schedule (time change last weekend),
now is falling.

Maven Dependency:
dependency>
            <groupId>com.aventstack</groupId>
            <artifactId>extentreports</artifactId>
            <version>3.0.2</version>
        </dependency>

______________

test failed log:
abr 03, 2017 11:55:08 AM com.aventstack.extentreports.utils.DateUtil parse
SEVERE: 
java.text.ParseException: Unparseable date: "Apr 3, 2017 11:54:58 AM"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at com.aventstack.extentreports.utils.DateUtil.parse(DateUtil.java:16)
	at com.aventstack.extentreports.reporter.converters.ExtentHtmlTestConverter$TestParserUtils.getStartTime(ExtentHtmlTestConverter.java:138)
	at com.aventstack.extentreports.reporter.converters.ExtentHtmlTestConverter.parseAndGetTest(ExtentHtmlTestConverter.java:68)
	at com.aventstack.extentreports.reporter.converters.ExtentHtmlTestConverter.parseAndGetTests(ExtentHtmlTestConverter.java:50)
	at com.aventstack.extentreports.reporter.converters.ExtentHtmlReporterConverter.parseAndGetModelCollection(ExtentHtmlReporterConverter.java:17)
	at com.aventstack.extentreports.reporter.ExtentHtmlReporter.parseReportBuildTestCollection(ExtentHtmlReporter.java:111)
	at com.aventstack.extentreports.reporter.ExtentHtmlReporter.start(ExtentHtmlReporter.java:102)
	at com.aventstack.extentreports.Report.attach(Report.java:51)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at com.aventstack.extentreports.ExtentReports.attachReporter(ExtentReports.java:66)
         ....

**Comment by anshooarora** [comment]
Can you please check with 3.0.4?

**Pull request merged**
