### PR TITLE
show selected categories as a pyramid

### PR DESCRIPTION
**Pull request by JephTheBest**
I find it nice to show:
- the test dscription on the categories-view
- to show selected categories as pyramid

### CODE REVIEW

**Comment by anshooarora** [comment]
@JephTheBest - can you include a test so I can check how the pyramid is built?

**Comment by email2vimalraj** [comment]
@JephTheBest : Also it would be great if you can attach the report which got generated with the pyramid view.

**Comment by JephTheBest** [comment]
@email2vimalraj : done
testngreport

**Comment by email2vimalraj** [comment]
@JephTheBest / @anshooarora : I'm not sure of the usecase on the pyramid show here. Is it just nice to show or does it add any value to the report?
Because, adding things would eventually add more to the file size. IMHO, We should pick and choose what is really required.

**Comment by JephTheBest** [comment]
@email2vimalraj : I thinks it could be a nice feature. 
https://martinfowler.com/bliki/TestPyramid.html

**Comment by email2vimalraj** [comment]
@JephTheBest : I agree with what Martin Fowler says about TestPyramid. By looking at the count itself, user can come to know where the major number of test cases goes on.

IMHO, adding the visual pyramid to the report is not value added.

**Comment by JephTheBest** [comment]
@email2vimalraj : what about this request -> show the test dscription on the categories-view

**Comment by email2vimalraj** [comment]
@JephTheBest : Is that not available already? I see the test name with status in the category view. I believe that should be enough. If we are adding a description, let's wait for the ask from the users.

@anshooarora : Your views?

**Comment by anshooarora** [comment]
The category distribution can be added in the category view itself.  We don't really need to create another view for this as its going to increase the template/file size.  Also, the pyramid would require much more real-estate on the UI so I would prefer a bar or pie chart.

**Pull request closed without merging**
